#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

"$(dirname "$0")/../gradlew" spotlessApply
npx prettier "$(dirname "$0")/../frontend" --ignore-path ".next"  --write

cd  "$(dirname "$0")/../frontend" && npx eslint --fix
git add -A
